polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
	# ex: /polls/
	url(r'^$', views.index, name='index'),
	# ex: /polls/5/
	url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
	# ex: /polls/5/results/
	url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
	# ex: /polls/5/vote/
	url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

scrsites/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from scrsites import views
from scrsites.books.views import search_form, search
from scrsites.contact.views import contact, contactThanks

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
	(r'^search_form/$', search_form),
    (r'^search/$', search),
	(r'^contact/$', contact),
	(r'^contact/thanks/$', contactThanks),
	(r'^$', views.scrnrAdmin), # Staff administrative screen
	(r'^scrn/scrnrAdmin/$', views.scrnrAdmin), # Staff administrative screen
	(r'^scrn/$', views.scrnr, { 'quickExit' : False }), # accumulate risk and pt info then exit
	(r'^scrn/quickExit/$', views.scrnr, {'quickExit' : True }), # Quick exit logic
	(r'^scrn/explanations/(\w+)/$', views.scrnrexpln),
	(r'^scrn/p0/$', views.p0),
	(r'^scrn/p1/$', views.p1),
	(r'^scrn/p2/$', views.p2),
	(r'^scrn/p3/$', views.p3),
	(r'^scrn/p3a/$', views.p3a),
	(r'^scrn/p3b/$', views.p3b),
	(r'^scrn/p3c/$', views.p3c),
	(r'^scrn/p4/$', views.p4),
	(r'^scrn/p4a/$', views.p4a),
	(r'^scrn/p4b/$', views.p4b),
	(r'^scrn/p5/$', views.p5),
	(r'^scrn/aboveAverageRisk/$', views.aboveAverageRisk),
	(r'^scrn/AverageRisk/$', views.AverageRisk),
	(r'^scrn/IndetermRisk/$', views.IndetermRisk),
	(r'^scrn/Completion/$', views.Completion),
	(r'^scrn/setDebugOptions/$', views.setDebugOptions),	
	(r'^display_meta/$', views.display_meta),
	url(r'^polls/', include('polls.urls', namespace="polls")),
	url(r'^polls2/', include('polls2.urls', namespace="polls2")),
	url(r'^multiquest/', include('multiquest.urls', namespace="multiquest")),
	url(r'^sudoku/', include('sudoku.urls', namespace="sudoku")),
    # Examples:
    # url(r'^$', 'scrsites.views.home', name='home'),
    # url(r'^scrsites/', include('scrsites.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

scrsites/books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()
	
    def __unicode__(self):
        return self.name
    
    class Meta:
        ordering = ["name"]
        
class Author(models.Model):
    salutation = models.CharField(max_length=10)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)
        
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.title
        

scrsites/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

class	nonPtInfo(models.Model):
	questionnaireTitle = models.CharField(max_length=100)
	questionnaireVersion = models.CharField(max_length=30, blank=True)
	questionnaireUpdate = models.CharField(max_length=30, blank=True)
	questionnaireEmail = models.CharField(max_length=30, blank=True)
	projectName = models.CharField(max_length=100)
	projectAbbrev = models.CharField(max_length=30, blank=True)
	projectContactPhone = models.CharField(max_length=30, blank=True)
	projectInternetResources = models.CharField(max_length=500, blank=True)
	projectInformedConsent = models.CharField(max_length=500, blank=True)
	genericInternetResources = models.CharField(max_length=500, blank=True)
	
class	PatientBRCADataEntry(models.Model):
	# p0
	patientName = models.CharField(max_length=30)
	birthDate = models.DateField()
	ptEmail = models.EmailField(max_length=75, blank=True)
	patientUniqueID = models.CharField(max_length=60, unique=True) # constructed
	entryDate = models.DateField()
	referralDecision = models.CharField(max_length=30)
	#questionnaire information
	questionnaireTitle = models.CharField(max_length=100, blank=True)
	questionnaireVersion = models.CharField(max_length=30, blank=True)
	questionnaireMode = models.CharField(max_length=30, blank=True) # e.g. "quickExit"
	questionnaireUpdate = models.CharField(max_length=30, blank=True) # version date
	
	# Callback number and associated checkbox
	callbackReq = models.BooleanField(max_length=30, blank=True)
	patientCallbackNumber = models.CharField(max_length=30, blank=True)
	# p1
	pHxOvCARiskGroupA = models.BooleanField( blank=True ) # *** not in any page
	pHxOvarianCA = models.CharField(max_length=30, blank=True) # page p1
	pHxFallopianCA = models.CharField(max_length=30, blank=True) # *** not in any page
	pHxPeritonealCA = models.CharField(max_length=30, blank=True) # *** not in any page
	fHxOvCARiskGroupA = models.CharField(max_length=30, blank=True) # *** not in any page
	fHxOvarianCA = models.CharField(max_length=30, blank=True) # page p2
	fHxFallopianCA = models.CharField(max_length=30, blank=True) # *** not in any page
	fHxPeritonealCA = models.CharField(max_length=30, blank=True) # *** not in any page
	# Recognized risk group variables
	recognizedRiskGroup = models.CharField(max_length=30, blank=True)	# page p4
	ashkenaziJewish = models.CharField(max_length=30, blank=True) # page p3b
	pHxBreastCA = models.CharField(max_length=30, blank=True) # page p3
	fHxBreastCA = models.CharField(max_length=30, blank=True)	# page p4
	fHxBrCASuscGene = models.CharField(max_length=30, blank=True)	# page p4
	fHxSufficient = models.CharField(max_length=30, blank=True)	# page p5
	pHxBrCARiskGroupA = models.CharField(max_length=30, blank=True) # *** not in any page
	pHxBrCALE50Years = models.CharField(max_length=30, blank=True)	# page p3a
	pHxBrCA3Neg = models.CharField(max_length=30, blank=True)	# page p3a
	pHxBrCAGT1PrimarySame = models.CharField(max_length=30, blank=True)	# page p3a
	pHxBrCAGT1PrimaryBoth = models.CharField(max_length=30, blank=True)	# page p3a
	pHxBrCADermMan = models.CharField(max_length=30, blank=True)	# page p3a
	pHxBrCARiskGroupB = models.CharField(max_length=30, blank=True) # *** not in any page
	pHxBrCAGE1RelBrCALE50Years = models.CharField(max_length=30, blank=True)	# page p3b
	pHxBrCAGE2RelBrPancCA = models.CharField(max_length=30, blank=True)	# page p3b
	pHxBrCARiskGroupC = models.CharField(max_length=30, blank=True) # *** not in any page
	pHxBrCAThyroidCA = models.CharField(max_length=30, blank=True)	# page p3c
	pHxBrCASarcoma = models.CharField(max_length=30, blank=True)	# page p3c
	pHxBrCAAdrenalCA = models.CharField(max_length=30, blank=True)	# page p3c
	pHxBrCAEndometrialCA = models.CharField(max_length=30, blank=True)	# page p3c
	pHxBrCAPancreaticCA = models.CharField(max_length=30, blank=True)	# page p3c
	pHxBrCABrainTumors = models.CharField(max_length=30, blank=True)	# page p3c
	pHxBrCAGastricCA = models.CharField(max_length=30, blank=True)	# page p3c
	pHxBrCALeukLymphoma = models.CharField(max_length=30, blank=True)	# page p3c
	fHxBrCARiskGroupA = models.CharField(max_length=30, blank=True) # *** not in any page
	fHxBrCAMale = models.CharField(max_length=30, blank=True)	# page p4a
	fHxBrCASameSideGE2 = models.CharField(max_length=30, blank=True)	# page p4a
	fHxBrCARiskGroupB = models.CharField(max_length=30, blank=True) # *** not in any page
	fHxBrCADermMan = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCAThyroidCA = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCASarcoma = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCAAdrenalCA = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCAEndometrialCA = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCAPancreaticCA = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCABrainTumors = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCAGastricCA = models.CharField(max_length=30, blank=True)	# page p4b
	fHxBrCALeukLymphoma = models.CharField(max_length=30, blank=True)	# page p4b
		
	def __unicode__(self):
		return self.patientName

class	RiskNames(models.Model): # Assocate risk ID with text for summary page
	riskID = models.CharField(max_length=30)
	riskDeclarYes = models.CharField(max_length=500)
	riskDeclarNo =  models.CharField(max_length=500)
	

scrsites/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False)
    message = forms.CharField(widget=forms.Textarea)

scrsites/forms.py
# Forms for screener pages
from django import forms
from django.forms.widgets import RadioSelect

class p0Form(forms.Form):
    patientName = forms.CharField(max_length=50, label='My name is (last, first)')
    birthDate = forms.DateField(label='My birth date is (mm/dd/yyyy)')
    ptEmail = forms.EmailField( required=False, label='My e-mail address is')

class p1Form(forms.Form):
    pHxOvarianCA = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')], 
    	label='Have you ever had ovarian cancer?')

class aboveAverageRiskForm(forms.Form):
	patientCallbackNumber = forms.CharField(max_length=30, required=False, label='Patient phone')
	callbackReq = forms.BooleanField( required=False, label='Call back request')
	
class AverageRiskForm(forms.Form):
	placeF = forms.CharField(max_length=30, required=False, label='Place holder')

class IndetermRiskForm(forms.Form):
	placeF = forms.CharField(max_length=30, required=False, label='Place holder')

class p2Form(forms.Form):
    fHxOvarianCA = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')],
    	label='Have any of your close blood relatives ever had ovarian cancer?')

class p3Form(forms.Form):
    pHxBreastCA = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')], 
    label="""Have you ever had <a title="Tap here for more information about breast cancer"
            href="{{urlprefix}}scrn/explanations/moreonbreastca">
        breast cancer or DCIS?</a>.""")

class p3aForm(forms.Form):
	pHxBrCALE50Years = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	pHxBrCA3Neg = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	pHxBrCAGT1PrimarySame = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	pHxBrCAGT1PrimaryBoth = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	pHxBrCADermMan = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])

class p3bForm(forms.Form):
	ashkenaziJewish = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	pHxBrCAGE1RelBrCALE50Years = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	pHxBrCAGE2RelBrPancCA = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])

class p3c_Agg_queryForm(forms.Form): # aggregate "yes" or "no" query
	none_of_the_above = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')],
		label='If you have had any of these cancers, click "yes" to select.')

class p3cForm(forms.Form):
	error_css_class = 'error'
	required_css_class = 'required'
	pHxBrCAThyroidCA = forms.BooleanField(required=False,
		label="Thyroid cancer?")
	pHxBrCASarcoma = forms.BooleanField(required=False,
		label="Sarcoma?")
	pHxBrCAAdrenalCA = forms.BooleanField(required=False,
		label="Adrenal cancer?")
	pHxBrCAEndometrialCA = forms.BooleanField(required=False,
		label="Cancer of the uterus?")
	pHxBrCAPancreaticCA = forms.BooleanField(required=False,
		label="Pancreatic cancer?")
	pHxBrCABrainTumors = forms.BooleanField(required=False,
		label="Brain tumors?")
	pHxBrCAGastricCA = forms.BooleanField(required=False,
		label="Stomach cancer?")
	pHxBrCALeukLymphoma = forms.BooleanField(required=False,
		label="Leukemia or lymphoma?")

class p4Form(forms.Form):
	recognizedRiskGroup = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	fHxBrCASuscGene = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	fHxBreastCA = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])

class p4aForm(forms.Form):
	fHxBrCAMale = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	fHxBrCASameSideGE2 = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])
	
class p4b_Agg_queryForm(forms.Form): # aggregate "yes" or "no" query
	none_of_the_above = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')],
		label='If that relative had any of these cancers, click "yes"')

class p4bForm(forms.Form):
	error_css_class = 'error'
	required_css_class = 'required'
	fHxBrCADermMan = forms.BooleanField(required=False,
		label="Breast cancer involving the skin overlying the breast?")
	fHxBrCAThyroidCA = forms.BooleanField(required=False,
		label="Thyroid cancer?")
	fHxBrCASarcoma = forms.BooleanField(required=False,
		label="Sarcoma?")
	fHxBrCAAdrenalCA = forms.BooleanField(required=False,
		label="Adrenal cancer?")
	fHxBrCAEndometrialCA = forms.BooleanField(required=False,
		label="Cancer of the uterus?")
	fHxBrCAPancreaticCA = forms.BooleanField(required=False,
		label="Pancreatic cancer?")
	fHxBrCABrainTumors = forms.BooleanField(required=False,
		label="Brain tumors?")
	fHxBrCAGastricCA = forms.BooleanField(required=False,
		label="Stomach cancer?")
	#Diffuse gastric cancer
	fHxBrCALeukLymphoma = forms.BooleanField(required=False,
		label="Leukemia or lymphoma?")

class p5Form(forms.Form):
	fHxSufficient = forms.ChoiceField(widget=forms.RadioSelect, choices=[('Yes', 'Yes'), ('No', 'No')])

class setDebugOptionsForm(forms.Form):
	specialDebugOutput = forms.BooleanField(required=False, label="Turn on special debug output.")

scrsites/books/views.py
# Create your views here.

from django.http import HttpResponse
from django.shortcuts import render
from scrsites.books.models import Book

def search_form(request):
    return render(request, 'search_form.html')
    
def search(request):
	error = False
	if 'q' in request.GET:
		q = request.GET['q']
		if not q:
			error = True
		else:
			books = Book.objects.filter(title__icontains=q)
			return render(request, 'search_results.html',
				{'books': books, 'query': q})
	return render(request, 'search_form.html',
		{'error': error})

scrsites/contact/views.py
from django.shortcuts import render
from django.http import HttpResponse
from scrsites.contact.forms import ContactForm
from django.http import HttpResponseRedirect
from django.core.mail import send_mail

def contact(request):
	if request.method == 'POST':
		form = ContactForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			request.session["subject"] = cd['subject']
			request.session["message"] = cd['message']
			request.session["email"] = cd['email']
#			send_mail(
#				cd['subject'],
#				cd['message'],
#				cd.get('email', 'noreply@example.com'),
#				['siteowner@example.com'],
#			)
			return HttpResponseRedirect('/contact/thanks/')
	else:
		form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
        return render(request, 'contact/contact_form.html', {'form': form})
	
def contactThanks(request):
	return HttpResponse("Thank you")

scrsites/templates/screener/base_page.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
	<head>
		<title> PAMF breast health screening questionnaire - Page {{this_page}}</title>
	</head>
{% include 'screener/header.html' %}
	{% autoescape off %}
	{{ preamble }}
	{% endautoescape %}
    {% if errmsg %}
		<p style="color: red;">
    	{{errmsg }}
		</p>
    {% endif %}
	    
	{% if form.errors %}
		<p style="color: red;">
			Please correct the error{{ form.errors|pluralize }} below.
		</p>
	{% endif %}
	<form action="" method="post" >{% csrf_token %}
	<table >
	<tr>
		<td>
		{% if field_style == 'as_table' %}		
			<table frame='border' rules='all' border='2px'>
				{{form.as_table}}
			</table>
		{% elif field_style == 'as_p' %}
			{{form.as_p }}	
		{% elif field_style == 'as_ul' %}
			<ul>
				{{form.as_ul}}
			</ul>
		{% endif %}
		<a href="{{urlprefix}}{{baseURL}}{{back_to}}">
		<button type="button">Back</button> </a>
		<input type="submit" value="Next">
	{% autoescape off %}
	{% if preamblepost %}
	{{ preamblepost }}
    {% endif %}
	{% endautoescape %}
		</td>
	{% if imageBaseURL %}
	<td width='50%'>
		<img src="{{ imageBaseURL }}femaleReproductive.png" alt='female reproductive system image' height="300" />
	</td>
	{% endif %}
	</tr>
	</table>

	</form>
	
    {% include 'screener/footer.html' %}

scrsites/templates/screener/header.html
	    <h2>{{pageTitle}}</h2>
	    <h5>{{pageSubTitle}}</h5>

<!--
Copyright 2012 Health Records for Everyone

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

scrsites/templates/screener/p0.html
{% extends 'screener/base_page_inclusion.html' %}

{% block preamble %}
    <p style='font-size:Large;'>
        The information you enter in this questionnaire is kept confidential. It is transmitted and stored securely only inside the
        PAMF network. It will not be visible to unauthorized individuals or shared on the internet.
    </p>
   <p>
        By entering your name and birth date below, you are confirming that:<ul>
            <li>You understand and accept the terms and conditions of use of information you enter into this questionnaire.</li>
            <li>You have not already had genetic testing for BRCA1 or BRCA2 mutations.</li>
        </ul>
    </p>
    {% ifequal computerT  'iPad' %}
    <p>
		Tap in the boxes below to display the keyboard and then type in your information.
    </p>
    {% endifequal %}
{% endblock  %}

<!--
Copyright 2012 Health Records for Everyone

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

scrsites/templates/screener/p3.html
	<head>
		<title> PAMF breast health screening questionnaire - Page 3</title>
	</head>
{% include 'screener/header.html' %}
<div>
    <p>
        Have you ever had <a title="Tap here for more information about breast cancer"
            href="{{urlprefix}}scrn/explanations/moreonbreastca">
        breast cancer or DCIS?</a>.
    </p>
	{% if diagMess %}
   <p>
    back to:  {{back_to}}
    diagMess:  {{diagMess}}
    </p>
	{% endif %}
    
    <table width='70%'>
				{% if form.errors %}
					<p style="color: red;">
						Please correct the error{{ form.errors|pluralize }} below.
					</p>
				{% endif %}
  	<form action="" method="post">{% csrf_token %}
		<div class="field">
            {{ form.pHxBreastCA.errors }}
            <label for="id_pHxBreastCA"></label>
            {{ form.pHxBreastCA }}
        </div>
			<a href="{{urlprefix}}scrn/{{back_to}}">Back</a>
			<input type="submit" value="Next">
	</form>
    </table>
    <p><i>

    </i></p>
    <br /><br />
    {% include 'screener/footer.html' %}
</div>

<!--
Copyright 2011 Health Records for Everyone

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

scrsites/templates/screener/p3a.html
	<head>
		<title> PAMF breast health screening questionnaire - Page 3a</title>
	</head>
{% include 'screener/header.html' %}
<div>
    <p><i>
        Please answer all of the following questions about your breast cancer:
    </i></p>
	{% if form.errors %}
		<p style="color: red;">
			Please correct the error{{ form.errors|pluralize }} below.
		</p>
	{% endif %}
<table frame='border' rules='all' border='2px'>
  	<form action="" method="post">{% csrf_token %}
		<div class="field">
            {{ form.pHxBrCALE50Years.errors }}
            <label for="id_pHxBrCALE50Years">Were you under 51 years old when your breast cancer was first diagnosed?</label>
            {{ form.pHxBrCALE50Years }}
        </div>
		<div class="field">
            {{ form.pHxBrCA3Neg.errors }}
            <label for="id_pHxBrCA3Neg">Was your cancer "triple negative", <i>without</i> receptors for estrogen, progesterone and HER2?</label>
            {{ form.pHxBrCA3Neg }}
        </div>
		<div class="field">
            {{ form.pHxBrCAGT1PrimarySame.errors }}
            <label for="id_pHxBrCAGT1PrimarySame">Was your cancer found in more than one location in the same breast?</label>
            {{ form.pHxBrCAGT1PrimarySame }}
        </div>
		<div class="field">
            {{ form.pHxBrCAGT1PrimaryBoth.errors }}
            <label for="id_pHxBrCAGT1PrimaryBoth">Have you had cancer in both breasts?</label>
            {{ form.pHxBrCAGT1PrimaryBoth }}
        </div>
		<div class="field">
            {{ form.pHxBrCADermMan.errors }}
            <label for="id_pHxBrCADermMan">Did your <a title="Tap here for more information about breast cancer involving skin overlying the breast" href="{{urlprefix}}scrn/explanations/skininbreastca">breast cancer involved the skin overlying the breast</a>?</label>
            {{ form.pHxBrCADermMan }}
        </div>
			<a href="{{urlprefix}}scrn/{{back_to}}">Back</a>
			<input type="submit" value="Next">
	</form>
     </table>
    <br /><br />
    {% include 'screener/footer.html' %}
</div>

<!--
Copyright 2011 Health Records for Everyone

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

scrsites/templates/screener/p5.html
	<head>
		<title> PAMF breast health screening questionnaire - Page 5</title>
	</head>
{% include 'screener/header.html' %}
<div>
    <p><i>
    If none of your female close blood relatives lived past age 45 years, estimates of BRCA mutation risk may be inaccurate.
    </i></p>
    <table>
  	<form action="" method="post">{% csrf_token %}
        <tr>
 			{{ form.fHxSufficient.errors }}
           <td width='50%' valign='center'>
                Have any of your female
                <a title="Tap here to see what we mean by close blood relatives for this survey"
                   href="{{urlprefix}}scrn/explanations/closebloodrelatives">close blood relatives</a>
                lived beyond age 45 years?
            <label for="id_fHxSufficient"></label>
  			{{ form.fHxSufficient }}
           </td>
        </tr>
        <tr>
           <td width='50%' valign='center'>
			<a href="{{urlprefix}}scrn/{{back_to}}" target="_self">
			Back </a>
			<input type="submit" value="Next">
           </td>
        </tr>
	</form>
    </table>
    <br /><br />
    {% include 'screener/footer.html' %}
</div>

<!--
Copyright 2011 Health Records for Everyone

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->